#ifndef CONF_h
#define CONF_h

#define SWITCH_PIN_NUMBER 4
#define SWITCH_PIN_REGISTER PINF
#define SWITCH_DDR_REGISTER DDRF
#define SWITCH_DDR_PORT PORTF

#define KB_PIN_NUMBER 6
#define KB_PIN_REGISTER PINB
#define KB_DDR_REGISTER DDRB

#define KB_SOFTPOWER_PIN_NUMBER 2
#define KB_SOFTPOWER_PIN_REGISTER PINB
#define KB_SOFTPOWER_DDR_REGISTER DDRB

#define HOST_PIN_NUMBER 5
#define HOST_PIN_REGISTER PINB
#define HOST_DDR_REGISTER DDRB

#define HOST_SOFTPOWER_PIN_NUMBER 4
#define HOST_SOFTPOWER_PIN_REGISTER PINB
#define HOST_SOFTPOWER_DDR_REGISTER DDRB

#endif